AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# Parameters:
#   Email:
#     Type: String
#   EmailKey:
#     Type: String
#   EmailTo:
#     Type: String
#   EmailHost:
#     Type: String
#     Default: 'smtp.gmail.com'

Resources:
  # See https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
  # for more info to see how to tune the lambda function configs based on your use case.
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java17
      Handler: com.example.lambdatemplate.App::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/lambdatemplate.jar
      # Environment:
      #   Variables:
      #     EMAIL: !Ref Email
      #     EMAIL_KEY: !Ref EmailKey
      #     EMAIL_TO: !Ref EmailTo
      #     EMAIL_HOST: !Ref EmailHost

      # Attach policies here to give the function permission to access other AWS resources if needed
      # See: https://github.com/awslabs/serverless-application-model/blob/master/docs/policy_templates.rst
      # eg:
      #Policies:
      # - S3ReadPolicy:
      #     BucketName: test-bucket