spring:
  application:
    name: template
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_KEY}
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
variables:
  emailto: ${EMAIL_TO}

next:
  lambda:
    lambda1arn: "arn:aws:lambda:us-east-2:339712758982:function:youtube-service-1"
    lambda2arn: "arn:aws:lambda:us-east-2:339712758982:function:youtube-service-2"
    lambda3arn: "arn:aws:lambda:us-east-2:339712758982:function:youtube-service-3"
    ecstaskarn: "arn:aws:iam::339712758982:role/ecs-task-execution-role"
    lambda5arn: "arn:aws:lambda:us-east-2:339712758982:function:youtube-service-5"
    lambda6arn: "arn:aws:lambda:us-east-2:339712758982:function:youtube-service-6"
ecs:
  cluster:
    name: "youtube-cluster" # Replace with your ECS cluster name
  task:
    executionRoleArn: "arn:aws:iam::339712758982:role/ecs-task-execution-role"