spring:
  application:
    name: template
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_KEY}
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
variables:
  emailto: ${EMAIL_TO}